"""Added autoincrement on ID to models.

Revision ID: 3cc7303c24b6
Revises: 4bb9d0c6143a
Create Date: 2019-10-18 19:24:56.379801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cc7303c24b6'
down_revision = '4bb9d0c6143a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'user', 'card', ['card_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    # ### end Alembic commands ###
