"""Added columns

Revision ID: 4bb9d0c6143a
Revises: e6745f848d04
Create Date: 2019-10-18 18:21:40.750745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bb9d0c6143a'
down_revision = 'e6745f848d04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bike', sa.Column('location', sa.String(), nullable=True))
    op.add_column('rental', sa.Column('return_date', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'user', 'card', ['card_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('rental', 'return_date')
    op.drop_column('bike', 'location')
    # ### end Alembic commands ###
