"""card table

Revision ID: e6745f848d04
Revises: e7f7e0ffeed0
Create Date: 2019-10-18 18:09:10.175772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6745f848d04'
down_revision = 'e7f7e0ffeed0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('card_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'card', ['card_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'card_id')
    # ### end Alembic commands ###
